### ISSUE TITLE
How to use the script

### ISSUE THREAD

**Issue by sj14** [gpestana/kapacitor-unit#1]
Hi and many thanks for the tool.
Unfortunately I am not able to get any results. The command given in the readme file does not work.  I am using the following command to run the script (inside the kapacitor-unit folder):

`./bin/kapacitor-unit -d ./sample/ -t ./sample/alert_1.tick `

and the output:
```
influxdb is up-to-date
Starting test_manager
kapacitor is up-to-date
```

I was not able to set an output file or to find any results of the test.

Thanks in advance,
Simon

**Comment by gpestana** [comment]
Hey @sj14!
Thanks for the interest :) The tool is not usable yet and quite in beta still. Interested in giving a hand? This weekend I might have time to push it forward for a usable version- at least with the simplest use case.

What are you trying to accomplish with kapacitor-unit?

**Comment by sj14** [comment]
I imagine a tool which allows to replay a stream and comparing the results of different tick scripts (are the alerts triggered correctly, no false positive/negative). Based on the results, the scripts can be adjusted and tested again.
But I'm new to the whole TICK stack and have to talk to my mentor next week :)

**Comment by gpestana** [comment]
@sj14 ping! Have you noticed the recent improvements? You should be able to test stream scripts now. Let me know what you think!

**Comment by sj14** [comment]
Thanks for the update :) I have already implemented an own process just for my needs. Maybe I am going to open source it but I'm not sure yet, needs some polishing and have to figure out if there is a demand for this. Furthermore, it is not kind of this unit test framework you are implementing, it is more a converter from CSV files to InfluxDB readable stuff and Kapacitor replay files :)

**Comment by gpestana** [comment]
Nice, sounds great! Do you think that your idea/implementation could be somehow adapted or added to kapacitor-unit? Ideas and PRs more than welcome 😄

**Comment by sj14** [comment]
I have uploaded a simple tool [here](https://github.com/sj14/lineprotocol).
As you can see it is nothing special and only handles the file conversion :)

**Comment by gpestana** [comment]
@sj14 Cool stuff! I will close this issue, if you feel like integrate the parsing part in kapacitor-unit, go ahead! It would be great to have it as a feature :)
