### ISSUE TITLE
How to check test results when replaying a recording?

### ISSUE THREAD

**Issue by gpestana** [gpestana/kapacitor-unit#10]
**Problem:**
Kapacitor endpoint `/kapacitor/v1/tasks/alert.tick` does not show information about the alerts triggered when replaying data. Although kapacitor may trigger the alert (based on the logs), the information is not mapped in the alert status. This behaviour is cumbersome for the development of #7.

**Possible solution:**
One way to solve this limitation would be to parse Kapacitor logs and use that information to compare with the expected results. Since it requires log parsing, it is not clean and potentially will have problems with different kapacitor versions.

**How to reproduce:**
(using _Kapacitor 1.0.1 (git: master 04f1ab3116b6bab27cbf63cb0e6b918fc77c7320)_)

1) Add following task to kapacitor:

```
var data = stream
	| from()
		.database('weather')
		.retentionPolicy('default')
		.measurement('temperature')

data
	|alert().id('Temperature')
		.message('Temperature alert')
		.warn(lambda: "temperature" > 80)
		.crit(lambda: "temperature" > 100)
		.stateChangesOnly()
    .log('/tmp/temperature.tick.log')
```

2) Start a recording

`/kapacitor/v1/recordings/stream`

3) Record data that will trigger an alert:

POST `/kapacitor/v1/write?db=weather&rp=default  temperature,location=us-midwest temperature=90` 

4) Replay the recording

POST `/kapacitor/v1/replays -d '{"task": "<task_name>", "recording": "'<recording_id>'", "clock": "real"}'`

5) Check outputs when replay has finished:

A) logs:

```
[alert_weather.tick:alert2] 2017/09/01 13:34:24 D! WARNING alert triggered id:Temperature msg:Temperature alert data:&{temperature map[location:us-midwest] [time temperature] [[2017-09-01 13:34:24.286546253 +0000 UTC 82]] <nil>}
[httpd] 172.21.0.1 - - [01/Sep/2017:13:34:24 +0000] "POST /kapacitor/v1/write?db=weather&rp=default HTTP/1.1" 204 0 "-" "curl/7.43.0" 44b93656-8f1a-11e7-86d3-000000000000 97
```

B) Task information at `/kapacitor/v1/tasks/alert.tick`:

```
...
    "node-stats": {
      "alert2": {
        "alerts_triggered": 0,
        "avg_exec_time_ns": 0,
        "collected": 0,
        "crits_triggered": 0,
        "emitted": 0,
        "infos_triggered": 0,
        "oks_triggered": 0,
        "warns_triggered": 0
      },
...
```

As seen above, the alert is triggered based on kapacitor logs but the task information does not show it.

**Comment by nathanielc** [comment]
When you use the API to get task data you can pass an optional replay-id parameter. The returned data will be in the context of that replay. See https://docs.influxdata.com/kapacitor/v1.3/api/api/#get-task

**Comment by gpestana** [comment]
@nathanielc perfect, thanks! That seems exactly what will solve this issue. Will try it out!

**Comment by gpestana** [comment]
@nathanielc thanks for the help!

I see in the docs that

"replay-id |   | Optional ID of a running replay. The returned task information will be in the context of the task for the running replay"

Does this mean that the context of the replay is lost when the replay finishes? It seems that's what is happening:

GET `/kapacitor/v1/tasks/alert_weather.tick?replay-id=123`
`
{"error": "no running replay with ID: 123"}
`

Would there be any way to keep the state of the replay after it is finished? I can open an issue in the kapacitor upstream for discussing about this feature.

**Comment by nathanielc** [comment]
@gpestana Hmm, yeah the state is lost when the replay finishes. Seems like  simple solution would be to store the final state (stats and all) in the local database when a replay finishes. That way it can be queried until its deleted. Please do open an issue on Kapacitor.

**Comment by gpestana** [comment]
@nathanielc yes, I got the same idea. Storing the state of the replay would be really helpful and should not be too hard. I will open an issue on Kapacitor's project and start the discussion. Thanks for the help!

**Comment by gpestana** [comment]
The feature that will allow inspecting stats from task has been merged in https://github.com/influxdata/kapacitor/pull/1614 and will be in the next Kapacitor release. Update README to include dependency on latest version of Capacitor
