### ISSUE TITLE
Getting "is a directory" error

### ISSUE THREAD

**Issue by austinbutler** [gpestana/kapacitor-unit#19]
I feel like I must be doing something really basic wrong...

If I pass a directory with tickscripts in it to kapacitor-unit it complains that it's a directory.
```txt
[abutler@dev kapacitor-unit]$ kapacitor-unit --tests tests/connections.yml --dir /opt/tickscripts/enabled/
  _                          _ _                                _ _
 | |                        (_) |                              (_) |
 | | ____ _ _ __   __ _  ___ _| |_ ___  _ __ ______ _   _ _ __  _| |_
 | |/ / _` | '_ \ / _` |/ __| | __/ _ \| '__|______| | | | '_ \| | __|
 |   < (_| | |_) | (_| | (__| | || (_) | |         | |_| | | | | | |_
 |_|\_\__,_| .__/ \__,_|\___|_|\__\___/|_|          \__,_|_| |_|_|\__|
           | |
           |_|
The unit test framework for TICK scripts (v0.8)

2018/03/16 21:16:51 Init Tests failed: read /opt/tickscripts/enabled/: is a directory
```

If I pass a tickscript file to kapacitor-unit it complains that it's _not_ a directory.
```txt
[abutler@dev kapacitor-unit]$ kapacitor-unit --tests tests/connections.yml --dir /opt/tickscripts/enabled/connections.tick
  _                          _ _                                _ _
 | |                        (_) |                              (_) |
 | | ____ _ _ __   __ _  ___ _| |_ ___  _ __ ______ _   _ _ __  _| |_
 | |/ / _` | '_ \ / _` |/ __| | __/ _ \| '__|______| | | | '_ \| | __|
 |   < (_| | |_) | (_| | (__| | || (_) | |         | |_| | | | | | |_
 |_|\_\__,_| .__/ \__,_|\___|_|\__\___/|_|          \__,_|_| |_|_|\__|
           | |
           |_|
The unit test framework for TICK scripts (v0.8)

2018/03/16 21:18:54 Init Tests failed: open /opt/tickscripts/enabled/connections.tick/: not a directory
```

**Comment by gpestana** [comment]
@austinbutler thanks for reporting! That seems quite interesting indeed. The `-dir` should point at the tick scripts directory, as you have in the first example. I will try to recreate the problem, but have you tried to use `-dir` instead of `--dir` ? Just in case :)

**Comment by gpestana** [comment]
@austinbutler I assume you managed to get this done, so I will close this issue. Please re-open with more information about the problem so we can help you.

**Comment by austinbutler** [comment]
@gpestana sorry about that, I had moved on to other work and am just now getting a chance to return to this. Using just `-dir` results in the same error.

**Comment by Anderen2** [comment]
@gpestana @austinbutler I hit the same issue myself, and after some head scratching and code-reading I found out that the code was looking for a "TaskName / task_name" name in the tests file, and when this was not defined it would be set to "" (aka. the -dir folder) (ref. https://github.com/gpestana/kapacitor-unit/blob/master/kapacitorunit.go#L87 and https://github.com/gpestana/kapacitor-unit/blob/master/test/test.go#L16 ). 

In my test file I had used the key "task_script" and not "task_name" as I followed the example on https://www.gpestana.com/blog/kapacitor-unit/ and not the one in the readme. Changing it to "task_name" fixed the issue for me.

**Comment by gpestana** [comment]
@Anderen2 Thank you for helping with this! If you want, go ahead and make a PR with the documentation (README.md) fix so you'll be a contributor for the help 👍 

Reopening this issue until the documentation is fixed.

**Comment by Anderen2** [comment]
Hi @gpestana , sorry for the slow response. 

The README.md on this project is correct, it is your blog-post which is wrong (And I do not think I'm able to create any PR against that :) )

**Comment by gpestana** [comment]
😅 alright, I will fix the blog post then! I will also close this issue, thanks! :)
