### ISSUE TITLE
Allow configurations to be set by ENV variables

### ISSUE THREAD

**Issue by vlaurenzano** [gpestana/kapacitor-unit#34]
Allowing for configurations to be set by environment variables will be beneficial for a few scenarios:

- Containerization of kapacitor-unit itself
- Using kapacitor unit as a library

Env variables should be checked first before cli configs which would override any env vars. 

Thoughts?

**Comment by gpestana** [comment]
Sounds very good! Do you have any spare cycles to implement this? (same for #35)

**Comment by vlaurenzano** [comment]
https://github.com/gpestana/kapacitor-unit/pull/36

**Comment by gpestana** [comment]
Closing as it has been merged. Thanks again @vlaurenzan!
